### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by piorphism** [DreiDe/GWP---Get-Whatsapp-Pictures#3]
When I try to run the script the following error appears: 'Uncaught TypeError: window.Store.Wap.profilePicFind is not a function' which is caused by 'let url = window.Store.Wap.profilePicFind(num + "@c.us");'. It seems like they have removed this function or renamed. Could you please clarify what is going on?

**Comment by ahagacv** [comment]
Same issue. Maybe Whatsapp changed class names?

**Comment by DreiDe** [comment]
I already looked into the code. The `profilePicFind` function is still present in app.js but it seems like it has been removed from the `Store.Wap` Object. Therefore it should still be possible to call it altought I couldn't figure out how to call it yet. If anyone finds a solution please share it.

**Comment by DreiDe** [comment]
It should work again now.
